#!/bin/sh
#

DIR=`dirname $0`/../
export JAVA_HOME=$DIR/Resources/jre${jre.version}.jre/Contents/Home
LAUNCHER_JAR=$( find $DIR/Resources/plugins -name org.eclipse.equinox.launcher_*.jar | tail -n1)

$JAVA_HOME/bin/java \
-showversion \
-XX:MaxPermSize=256m \
-Xms1024m \
-Xmx1024m \
-XstartOnFirstThread \
-Dorg.eclipse.swt.internal.carbon.smallFonts \
-Dosgi.requiredJavaVersion=1.7 \
-Dosgi.instance.area=@user.home/curators-workspace \
-Djargon.debug=0 \
-jar $LAUNCHER_JAR
