<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="crosswalk"
    nsURI="http://lib.unc.edu/schemas/crosswalk" nsPrefix="walk">
  <eClassifiers xsi:type="ecore:EClass" name="TabbedDataField" eSuperTypes="#//DataField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ColumnNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrimWhitespace" eSuperTypes="#//WalkWidget #//Output #//Input"/>
  <eClassifiers xsi:type="ecore:EClass" name="CrossWalk" eSuperTypes="#//SchemaProvider #//MappingContainer #//Editable">
    <eOperations name="getProject" lowerBound="1" eType="#//IProject" eExceptions="#//DataException"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataSource" lowerBound="1"
        eType="#//DataSource" containment="true" eOpposite="#//DataSource/Walk"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputElement" abstract="true" interface="true">
    <eOperations name="updateRecord" lowerBound="1">
      <eParameters name="record" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Walk" eType="#//SchemaProvider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WalkWidget" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Walk" lowerBound="1" eType="#//SchemaProvider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" abstract="true" interface="true">
    <eOperations name="GoToExample" eExceptions="#//DataException #//RecordOutOfRangeException"/>
    <eOperations name="NextRecord" lowerBound="1" eExceptions="#//DataException #//RecordOutOfRangeException"/>
    <eOperations name="Reset" lowerBound="1" eExceptions="#//DataException"/>
    <eOperations name="getRecordID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getFieldValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="field" lowerBound="1" eType="#//DataField"/>
    </eOperations>
    <eOperations name="initializeDataFields" lowerBound="1" eExceptions="#//DataException"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Walk" lowerBound="1" eType="#//CrossWalk"
        eOpposite="#//CrossWalk/DataSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//DataField" containment="true" eOpposite="#//DataField/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataField" eSuperTypes="#//Output">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//DataSource"
        eOpposite="#//DataSource/fields"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DataException" instanceClassName="crosswalk.DataException"/>
  <eClassifiers xsi:type="ecore:EClass" name="Output" abstract="true" interface="true">
    <eOperations name="getResult" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        eExceptions="#//DataException"/>
    <eOperations name="getOutputEDataType" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" abstract="true" interface="true">
    <eOperations name="getInputEDataType" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Output" eType="#//Output"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IProject" instanceClassName="org.eclipse.core.resources.IProject"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IFile" instanceClassName="org.eclipse.core.resources.IFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="RecordMatcherStrategy" abstract="true"
      interface="true" eSuperTypes="#//WalkWidget">
    <eOperations name="getMatches" lowerBound="1" eType="#//RecordMatches"/>
    <eOperations name="run" lowerBound="1" eExceptions="#//DataException"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OriginalNameRecordMatcher" eSuperTypes="#//RecordMatcherStrategy #//Input">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caseSensitive" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeFileExtension" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseFolder" eType="#//IFolder"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="RecordMatches" instanceClassName="crosswalk.RecordMatches"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IFolder" instanceClassName="org.eclipse.core.resources.IFolder"/>
  <eClassifiers xsi:type="ecore:EDataType" name="RecordOutOfRangeException" instanceClassName="crosswalk.RecordOutOfRangeException"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateRecognizer" eSuperTypes="#//WalkWidget #//Output #//Input">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Formats" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="yy-MM-dd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//Output #//WalkWidget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelimitedFile" eSuperTypes="#//DataSource">
    <eOperations name="GoToRecord" eExceptions="#//DataException #//RecordOutOfRangeException">
      <eParameters name="RowNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SourceFile" lowerBound="1"
        eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataRow" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headerRow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textEncoding" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="utf-8"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldDelimiter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar" defaultValueLiteral=","/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textDelimiter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"
        defaultValueLiteral="&quot;" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappedElement" eSuperTypes="#//OutputElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childElements" upperBound="-1"
        eType="#//MappedElement" containment="true" eOpposite="#//MappedElement/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//MappedAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappedFeature" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//MappedElement"
        eOpposite="#//MappedElement/childElements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappedAttribute" eSuperTypes="#//OutputElement #//Input">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappedFeature" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conversionStrategy" eType="#//ConversionStrategy"
        unsettable="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConversionStrategy" abstract="true"
      interface="true">
    <eOperations name="convert" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eParameters name="input" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="getInputDataType" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
    <eOperations name="getOutputDataType" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateToISO8601StringConversion" eSuperTypes="#//ConversionStrategy"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dictionary" eSuperTypes="#//SchemaProvider #//Editable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//MetadataBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vocabularies" upperBound="-1"
        eType="#//Vocabulary" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetadataBlock" eSuperTypes="#//OutputElement #//MappingContainer #//FormElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//InputField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vocabulary">
    <eOperations name="getTerms" lowerBound="1">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="broaderTerm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getCompletions">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="prefix" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputField" eSuperTypes="#//Output #//Input">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemaProvider" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputType" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingContainer" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgets" ordered="false"
        upperBound="-1" eType="#//WalkWidget" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" ordered="false"
        upperBound="-1" eType="#//OutputElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditingContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//Editable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Editable" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Form" eSuperTypes="#//Editable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//FormElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormElement" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="java.net.URI"/>
  <eClassifiers xsi:type="ecore:EClass" name="Paragraph" eSuperTypes="#//FormElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="heading" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
